Clarification re repeated addContextListener and addIntentListener calls
finos/FDC3 pull request #1394
Opened 2024-10-18 16:18 UTC by kemerava

Closes #1390 

Based on the discussion on the issue, adding the clarification to the standard on the expected behavior when multiple calls are made to addContextListener and addIntentListener 

@michael-bowen-sc

2024-10-21 12:16 UTC, kriswest requested changes
Good job! Personally, I think that we triggering of all listeners is currently a MUST and should remain so (meaning the SHOULDs in the this PR become MUSTs to explicitly state that).

I also wonder if we need to add a comment about reconnection. If a web app is refreshed it needs to add new handlers as the old ones will be fone - the DA should be tracking the lifecycle of the app and considering them to have been removed if the app reloads/navigates/reconnects. That generally only applies to web apps as most others don't 'reconnect' or 'refresh' in a way that would wipe out their handler functions

2024-10-22 10:40 UTC, bingenito commented
I see a mix of resolvererror and resolveerror in text and anchor links.

2024-10-22 17:20 UTC, kriswest commented on docs/api/ref/DesktopAgent.md
> + Adding multiple intent listeners on the same type MUST be rejected with the [`ResolverError.IntentListenerConflict`](Errors#resolveerror), unless the previous listener was removed first though [`lis
```suggestion
 Adding multiple intent listeners on the same type MUST be rejected with the [`ResolveError.IntentListenerConflict`](Errors#resolveerror), unless the previous listener was removed first though [`listener.unsubscribe`](Types#unsubscribe)
```

2024-10-22 17:21 UTC, kriswest commented on src/api/Channel.ts
> +   * Adding multiple context listeners on the same or overlapping types (i.e. named type and null type) SHOULD be allowed, and SHOULD trigger all contextHandlers when a relevant context type is broad
```suggestion
   * Adding multiple context listeners on the same or overlapping types (i.e. named type and null type) SHOULD be allowed, and SHOULD trigger all context handlers when a relevant context type is broadcast on the current channel.
```

2024-10-22 17:21 UTC, kriswest commented on src/api/DesktopAgent.ts
> +   * Adding multiple intent listeners on the same type MUST be rejected with the `ResolverError.IntentListenerConflict`, unless the previous listener was removed first though `listener.unsubscribe`
```suggestion
   * Adding multiple intent listeners on the same type MUST be rejected with the `ResolveError.IntentListenerConflict`, unless the previous listener was removed first though `listener.unsubscribe`
```

2024-10-22 17:23 UTC, kriswest commented
> I see a mix of resolvererror and resolveerror in text and anchor links.

Good 👀 @bingenito - I missed several of those. Added to suggestions

2024-10-25 17:47 UTC, kemerava commented on docs/api/ref/Channel.md
> +Adding multiple context listeners on the same or overlapping types (i.e. specific `contextType` and `null` type) SHOULD be allowed, and SHOULD trigger all ContextHandlers when a relevant context type
Changed the SHOULD to MUST - @kriswest would you like to wait until the tests are in the conformance to close this comment?

2024-10-25 17:48 UTC, kemerava commented on src/api/DesktopAgent.ts
> +   * Adding multiple context listeners on the same or overlapping types (i.e. named type and null type) SHOULD be allowed, and SHOULD trigger all contextHandlers when a relevant context type is broad
Changed

2024-10-25 17:49 UTC, bingenito approved these changes

2024-10-25 18:23 UTC, kemerava commented on docs/api/ref/Channel.md
> +Adding multiple context listeners on the same or overlapping types (i.e. specific `contextType` and `null` type) SHOULD be allowed, and SHOULD trigger all ContextHandlers when a relevant context type
I also added the test definitions to the files you mentioned

2024-11-22 20:02 UTC, kemerava commented on docs/api/ref/Channel.md
> +Adding multiple context listeners on the same or overlapping types (i.e. specific `contextType` and `null` type) SHOULD be allowed, and SHOULD trigger all ContextHandlers when a relevant context type
@kriswest let me know if anything else needs adding here or if it can be resolved

2024-11-25 11:37 UTC, kriswest commented
> @kriswest In terms of the reconnection, I think that there a case which can to be made for Desktop Agent to keep the listeners in memory at least for a short period of time. Not sure as much for web apps, but for others, depending on which method of connection is used, it is possible that the app temporarily lost the connection, and I am not sure if it makes sense to always ask apps to reconnect.
> This is my scenario, for example, if Desktop Agent is determining the app connection based on the heartbeats from the app, and then the app disconnects, then the behavior is slightly undererministic, where Desktop Agent might have already "noticed" that the app has disconnected, and removed the listeners, or it has not, and then the listeners are still there, and then the app unnecessarily sending more calls to DA. Of course, even with keeping listeners in memory we cannot guarantee for sure if that senario would not happen. We can also think about introducing an endpoint which would list all the listenerIds which DA has for the given app, this way the app can verify if it is missing some listeners or if there are some which are no longer needed and can be cleaned up
> Please let me know what you think!

Apologies, for the delay in responding to your question on this. Disconnection is an awkward topic for FDC3 as what it means could vary greatly between implementations. In the classic container implementations for web apps, its doesn't really happen other than via the lifecycle of the application. That's because the Desktop Agent tends to be provided by a local service of some sort and is therefore not affected by the network connection... If it goes down, the Desktop Agent API is still available (the connection between the app and Desktop Agent is unaffected), listeners remain valid etc.. 

I suspect that this will be the same for most FDC3 for the Web implementations... if the Desktop Agent was already loaded and connected to, then the network connection going down doesn't affect its ability to provide interoperability between windows! Of course, there will be exceptions: Desktop Agent implementations which rely on a remote web service and situations where the Desktop Agent window is refreshed and reloads. I suspect these cases need thinking about. In both cases there is potentially a need for some sort of event to pass back for either the apps or the `getAgent` code to handle. A new connection to the DA needs to be set up (as we'll lose the Message Ports in the later case).

I think we'd be well advised to trigger the connection flow afresh - the DA might come back with a different config for apps for example. The alternative is that the Desktop Agent. Whether the getAgent code retains listener or requires new ones to be set-up at that point is something we'll need to consider. `getAgent()` will certainly need to re-register the listeners with the DA, even if the app doesn't have to re-add them.

When it comes to native apps and disconnection, we will usually be talking about a local service that provides access to the DA going down or being restarted. In those cases, new connections (and polling for connection) will likely be needed. Whether listeners need to be readded or not feels like something we should discuss as it should probably be implemented consistently (and hence handled in a standardized way).

At the very least we'll need to think about adding an (`addEventListener`) event for disconnect and reconnect and then discuss how that should be handled. If what I've said here makes sense, would you be up for raising an issue for the Standards Working Group to discuss? It  might help to enumerate all the different types of disconnection that could occur and figure out which need solutions (I think the DA going away, at least temporarily, is the primary one to address).

2024-11-25 11:41 UTC, kriswest commented
P.S. I think this PR is ready to go - the only thing holding it up is the fact that we closed the 2.2 scope and this does introduce a new error that MUST be thrown. However, it's not a big change and I would be happy to consider a motion to put it into 2.2 (which is currently blocked by completing the `getAgent` implementation work) if participants wanted to get it implemented and there were no objections or existing examples of alternative ways of handling intent listener conflicts that another participant wanted to to preserve.

2024-12-06 19:13 UTC, kemerava commented
> P.S. I think this PR is ready to go - the only thing holding it up is the fact that we closed the 2.2 scope and this does introduce a new error that MUST be thrown. However, it's not a big change and I would be happy to consider a motion to put it into 2.2 (which is currently blocked by completing the `getAgent` implementation work) if participants wanted to get it implemented and there were no objections or existing examples of alternative ways of handling intent listener conflicts that another participant wanted to to preserve.

@kriswest has there been consensus on this one? In my view, it is a pretty small change, but if we want to hold it off until 2.3 that is fine as well

2024-12-10 16:54 UTC, kriswest commented
We were set to hold off for 2.3 for purely procedural reasons (we voted to close the scope). However, I agree this is small and fixes an existing problem and could go in for 2.2. This PR could be called a breaking change as it introduces a new error that could be returned on existing calls to `raiseIntent` and `raiseIntentForContext`. However, you would previously have been faced with unstandardized behaviour if you tried to add a listener for the same intent multiple times and DAs might have returned a non-standard error, overwritten the handler or something else. Hence, I think bringing this in is a better situation.

Regardless it will need approval by the SWG which we can do at the next meeting.

2025-05-02 18:21 UTC, kemerava commented on website/versioned_docs/version-2.0/api/conformance/App-Channel-Tests.md
> +## Multipe listeners On The Same Or Overlapping Ccontext types
Done, not sure why they ended up there

2025-05-02 18:21 UTC, kemerava commented on website/versioned_docs/version-2.1/api/conformance/User-Channel-Tests.md
> +## Broadcast With Multiple Listeners On The Same or Overlapping Types
Done, thanks!

2025-05-02 18:43 UTC, kemerava commented
> Conformance test additions need moving into the next version of the docs. Also I think we're missing a test that triggers `IntentListenerConflict`.

@kriswest thank you for the review! Added the tests and fixed the location of the previous ones. Could you please re-review? Thanks!

2025-05-07 16:42 UTC, kriswest approved these changes
LGTM - I wondered whether anything needed to be added to the compliance table at: https://fdc3.finos.org/docs/api/spec#desktop-agent-api-standard-compliance
for the new MUSTs added in this PR. However, on reviewing that list I note that existing points:

> - Include implementations of the following [Desktop Agent](https://fdc3.finos.org/docs/api/ref/DesktopAgent) API functions, as defined in this Standard

...

> - Return (JavaScript or platform appropriate) Error Objects with messages from the [ChannelError](https://fdc3.finos.org/docs/api/ref/Errors#channelerror), [OpenError](https://fdc3.finos.org/docs/api/ref/Errors#openerror), [ResolveError](https://fdc3.finos.org/docs/api/ref/Errors#resolveerror) and [ResultError](https://fdc3.finos.org/docs/api/ref/Errors#resulterror) enumerations as appropriate.

Already import the requirement from the reference material and that is how it is dealt with for other similar requirements. hence, I think good to merge after review by @finos/fdc3-editors (@novavi or @hughtroeger could you take a look please)

2025-06-11 13:38 UTC, hughtroeger commented on CHANGELOG.md
> +  - resolves ([#1488](https://github.com/finos/FDC3/issues/1488))
Are these intended as part of this PR?

2025-06-11 13:50 UTC, hughtroeger commented on website/docs/api/conformance/App-Channel-Tests.md
> +| A   | 6.Receive Context    | The handlers added in step 2 and 3 will receive the instrument context. Ensure that the instrument received by A is identical to that sent by B.  |
Nitpick but there are no spaces between the numerical bullet points and the step names, there are spaces in the other test step tables.

2025-06-11 14:09 UTC, novavi approved these changes
Minor comments

2025-06-11 14:09 UTC, novavi commented on packages/fdc3-standard/src/api/DesktopAgent.ts
> +   * Adding multiple context listeners on the same or overlapping types (i.e. named type and null type) MUST be allowed, and MUST trigger all contextHandlers when a relevant context type is broadcast
Missing space character between words at:

`fdc3.addIntentListener`API

2025-06-11 14:09 UTC, novavi commented on packages/fdc3-standard/src/api/Errors.ts
> +  IntentListenerConflict = "IntentListenerConflict",
Should use single quotes for consistency with rest of file

2025-06-11 14:09 UTC, novavi commented on packages/fdc3-standard/src/api/DesktopAgent.ts
> +   * Adding multiple intent listeners on the same type MUST be rejected with the `ResolveError.IntentListenerConflict`, unless the previous listener was removed first though `listener.unsubscribe`
Should `listener.unsubscribe` be `listener.unsubscribe()` (for consistency with references to other methods/functions above e.g. `getResult()`) ?

2025-06-11 14:09 UTC, novavi commented on website/docs/api/conformance/User-Channel-Tests.md
> +| A   | 1.addContextListeners | A sets up two Context Listeners.  One _untyped_ and one for `fdc3.contact` by calling:  `addContextListener (null, handler1)` <br/> `addContextListener ("fdc3.contact"
Remove spaces between method names and open braces:  `addContextListener (null, handler1)` and `addContextListener ("fdc3.contact", handler2)`

2025-06-11 14:09 UTC, novavi commented on website/versioned_docs/version-2.2/api/conformance/App-Channel-Tests.md
> +| A   | 2. Add Context Listener | Add a _typed_ context listener for `fdc3.instrument`, using: <br />`await testChannel.addContextListener("fdc3.instrument",handler)`|
Missing space between comma and argument: `("fdc3.instrument",handler)`

2025-06-11 14:51 UTC, hughtroeger commented on website/docs/api/conformance/User-Channel-Tests.md
> +| A   | 5.Receive Context    | A's `fdc3.contact` object matches the one broadcast  by B, both handlers from step 1 are triggered, and broadcast arrives on the correct listener.   |
No spaces between numerical bullet points and step names.

2025-06-11 14:52 UTC, hughtroeger commented on website/docs/api/conformance/User-Channel-Tests.md
> +| A   | 5.Receive Context    | A's `fdc3.contact` object matches the one broadcast  by B, both handlers from step 1 are triggered, and broadcast arrives on the correct listener.   |
What does 'broadcast arrives on the correct listener' mean in this context if both listeners are supposed to be triggered?

2025-06-13 08:53 UTC, kriswest commented on CHANGELOG.md
> +  - resolves ([#1488](https://github.com/finos/FDC3/issues/1488))
I think it'd take a rebase to remove this from the diff. These went into main after this PR was started and then leak into the diff after being merged (as it still looks like a diff from the base of the branch). We can ignore

2025-06-13 08:54 UTC, kriswest commented on packages/fdc3-standard/src/api/DesktopAgent.ts
> +   * Adding multiple intent listeners on the same type MUST be rejected with the `ResolveError.IntentListenerConflict`, unless the previous listener was removed first though `listener.unsubscribe`
```suggestion
   * Adding multiple intent listeners on the same type MUST be rejected with the `ResolveError.IntentListenerConflict`, unless the previous listener was removed first though `listener.unsubscribe()`
```

2025-06-13 08:54 UTC, kriswest commented on packages/fdc3-standard/src/api/DesktopAgent.ts
> +   * Adding multiple context listeners on the same or overlapping types (i.e. named type and null type) MUST be allowed, and MUST trigger all contextHandlers when a relevant context type is broadcast
```suggestion
   * Adding multiple context listeners on the same or overlapping types (i.e. named type and null type) MUST be allowed, and MUST trigger all contextHandlers when a relevant context type is broadcast on the current user channel. Please note, that this behavior differes from `fdc3.addIntentListener` API call; refer to the relevant documentation for more detials. 
```

2025-06-13 08:54 UTC, kriswest commented on packages/fdc3-standard/src/api/Errors.ts
> +  IntentListenerConflict = "IntentListenerConflict",
```suggestion
  IntentListenerConflict = 'IntentListenerConflict',
```

2025-06-13 08:55 UTC, kriswest commented on website/docs/api/conformance/App-Channel-Tests.md
> +| A   | 6.Receive Context    | The handlers added in step 2 and 3 will receive the instrument context. Ensure that the instrument received by A is identical to that sent by B.  |
```suggestion
| App | Step               | Details                                                                    |
|-----|--------------------|----------------------------------------------------------------------------|
| A   | 1. Retrieve `Channel`    |Retrieve a `Channel` object representing an 'App' channel called `test-channel` using: <br/>`const testChannel = await fdc3.getOrCreateChannel("test-channel")` |
| A   | 2. Add Context Listener |Add an _untyped_ context listener to the channel, using: <br/> ![2.0](https://img.shields.io/badge/FDC3-2.0-blue) `await testChannel.addContextListener(null, handler1)` <br/>![1.2](https://img.shields.io/badge/FDC3-1.2-green) `testChannel.addContextListener(null, handler1)` |
| A   | 3. Add Context Listener |Add a _typed_ context listener for `fdc3.instrument` with a different handler, using: <br/> ![2.0](https://img.shields.io/badge/FDC3-2.0-blue) `await testChannel.addContextListener("fdc3.instrument", handler2)` <br/>![1.2](https://img.shields.io/badge/FDC3-1.2-green) `testChannel.addContextListener("fdc3.instrument", handler2)`|
| B   | 4. Retrieve `Channel`     | Retrieve a `Channel` object representing the same 'App' channel A did (`test-channel`)|
| B   | 5. Broadcast          | Broadcast an `fdc3.instrument` Context to the channel with: <br/>`testChannel.broadcast(<fdc3.instrument context>)`|
| A   | 6. Receive Context    | The handlers added in step 2 and 3 will receive the instrument context. Ensure that the instrument received by A is identical to that sent by B.  |
```

2025-06-13 08:56 UTC, kriswest commented on website/docs/api/conformance/User-Channel-Tests.md
> +| A   | 1.addContextListeners | A sets up two Context Listeners.  One _untyped_ and one for `fdc3.contact` by calling:  `addContextListener (null, handler1)` <br/> `addContextListener ("fdc3.contact"
```suggestion
| A   | 1. addContextListeners | A sets up two Context Listeners.  One _untyped_ and one for `fdc3.contact` by calling:  `addContextListener(null, handler1)` <br/> `addContextListener("fdc3.contact", handler2)` <br/>![1.2](https://img.shields.io/badge/FDC3-1.2-green) A `Listener` object is returned for each.  <br />![2.0](https://img.shields.io/badge/FDC3-2.0-blue) A promise resolving a `Listener` object is returned for each. <br />Check that this has an `unsubscribe` method for each.  |
```

2025-06-13 08:57 UTC, kriswest commented on website/docs/api/conformance/User-Channel-Tests.md
> +| A   | 5.Receive Context    | A's `fdc3.contact` object matches the one broadcast  by B, both handlers from step 1 are triggered, and broadcast arrives on the correct listener.   |
```suggestion
| A   | 2. joinUserChannel     |A joins the first available user channel using: <br/>![1.2](https://img.shields.io/badge/FDC3-1.2-green) `getSystemChannels()` Check channels are returned. <br/>![2.0](https://img.shields.io/badge/FDC3-2.0-blue) `getUserChannels()` Check **user** channels are returned.<br/>Call `fdc3.joinChannel()` on the first non-global channel.|
| B   | 3. joinUserChannel     |B joins the same channel as A, via the same process in 2. |
| B   | 4. Broadcast          |`fdc3.broadcast(<contact context>)` . |
| A   | 5. Receive Context    | A's `fdc3.contact` object matches the one broadcast  by B, both handlers from step 1 are triggered, and broadcast arrives on the correct listener.   |
```

2025-06-13 08:57 UTC, kriswest commented on website/versioned_docs/version-2.2/api/conformance/App-Channel-Tests.md
> +| A   | 2. Add Context Listener | Add a _typed_ context listener for `fdc3.instrument`, using: <br />`await testChannel.addContextListener("fdc3.instrument",handler)`|
```suggestion
| A   | 2. Add Context Listener | Add a _typed_ context listener for `fdc3.instrument`, using: <br />`await testChannel.addContextListener("fdc3.instrument", handler)`|
```

2025-06-13 08:58 UTC, kriswest commented
@hughtroeger and @novavi I've applied your suggestions, could one of you sign off again for @finos/fdc3-editors

2025-06-26 07:38 UTC, kriswest commented
@finos/fdc3-editors (@hughtroeger and @novavi) I think this is just waiting for your sign-off in order to merge.

2025-07-18 15:56 UTC, novavi commented on packages/fdc3-standard/src/api/DesktopAgent.ts
> +   * Adding multiple context listeners on the same or overlapping types (i.e. named type and null type) MUST be allowed, and MUST trigger all contextHandlers when a relevant context type is broadcast
Typo - 'differes' should be 'differs'

2025-07-25 16:37 UTC, kemerava commented on packages/fdc3-standard/src/api/DesktopAgent.ts
> +   * Adding multiple context listeners on the same or overlapping types (i.e. named type and null type) MUST be allowed, and MUST trigger all contextHandlers when a relevant context type is broadcast
Thanks, @novavi! Fixed it

2025-08-13 13:26 UTC, kriswest commented
@novavi need you to re-approve this so we can merge (currently blocked)

2025-08-13 13:53 UTC, kriswest approved these changes
LGTM

2025-08-13 13:53 UTC, julianna-ciq approved these changes
lgtm

2025-08-13 14:01 UTC, merged