Fdc3 for web impl test policy
finos/FDC3 pull request #1480
Opened 2024-12-19 13:02 UTC by robmoffat

## Describe your change

Adds testing policy for FDC3-On-The-Web quality control for FDC3 2.2

### Related Issue

- https://github.com/finos/FDC3/issues/810

## Contributor License Agreement

- [X] I acknowledge that a contributor license agreement is required and that I have one in place or will seek to put one in place ASAP.

## Review Checklist

- [x] **Issue**: If a change was made to the FDC3 Standard, was an issue linked above?
- [x] **CHANGELOG**: Is a *CHANGELOG.md* entry included?

2025-01-07 14:57 UTC, kriswest requested changes
Thanks for taking this on. 

I don't quite understand the latter section of the policy, which appears to conflict with the first part (which breaks out sub-module policies). See the comment - I may be readingit wrong (in which case it could be clarified).

2025-01-07 15:12 UTC, robmoffat commented on CONTRIBUTING.md
> +  * All code must be tested (coverage is reported in the PR comments)
yes... I didn't mean to say that every line should be covered.  Is this how it came across?

2025-01-07 15:21 UTC, kriswest commented on CONTRIBUTING.md
> +  * All code must be tested (coverage is reported in the PR comments)
Yeah, to me 'all code must be tested' sounds like every line and branch (which is tough). Perhaps a qualifier like 'All code _units_ or _modules_ ...'.

Perhaps some slight softening would also make sense (replace 'must' with 'should')?

2025-01-14 16:15 UTC, robmoffat commented on CONTRIBUTING.md
> +  * All code must be tested (coverage is reported in the PR comments)
```suggestion
  * Code should have tests (coverage is reported in the PR comments)
```

2025-01-14 16:15 UTC, robmoffat commented on CONTRIBUTING.md
> +  * All new code must be covered by tests.
```suggestion
```

2025-01-14 16:16 UTC, kriswest approved these changes
LGTM!

2025-01-14 16:16 UTC, robmoffat commented
Can an FDC3 maintainer take a look at this new testing policy please?

2025-01-14 16:17 UTC, julianna-ciq approved these changes

2025-01-16 09:32 UTC, mistryvinay approved these changes
LGTM 👍

2025-01-16 11:41 UTC, merged