PR For Issue 243 Allow Specification of Channel MetaData during Channel Creation
finos/FDC3 pull request #244
Opened 2020-09-16 16:47 UTC by sgd2z

https://github.com/finos/FDC3/issues/243

2020-09-16 17:00 UTC, rikoe requested changes

2020-09-16 17:00 UTC, rikoe commented on src/api/DesktopAgent.ts
> +     *
displayMetadata (not "MetaData")

2020-09-16 17:00 UTC, rikoe commented on src/api/DesktopAgent.ts
> +    getOrCreateChannel(channelId: string, displayMetaData?: DisplayMetaData): Promise<Channel>;
`displayMetadata?: DisplayMetadata`

2020-10-22 10:37 UTC, rikoe commented
@sgd2z I propose we close this for the time being, as we haven't reached consensus for this one and it isn't currently planned for 1.2 (if I am correct), and this particular approach was observed as somewhat ambiguous/confusing by the standards working group.

2020-10-22 12:48 UTC, sgd2z commented
> @sgd2z I propose we close this for the time being, as we haven't reached consensus for this one and it isn't currently planned for 1.2 (if I am correct), and this particular approach was observed as somewhat ambiguous/confusing by the standards working group.

I have a poll in the issue itself on which of two options to pick. I'll update the PR accordingly once a decision is made.

2020-10-29 01:36 UTC, nkolba commented
@sgd2z  - I've commented on the related issue.  We haven't gotten response on the poll.  Should we close issue and PR for now and take up again when we have more supporting use cases in this area?

2021-07-22 14:07 UTC, kriswest commented
Closing as the associated issue was closed

2021-07-22 14:07 UTC, closed without merging