Export costs for DesktopAgent methods for ES6 usage
finos/FDC3 pull request #266
Opened 2020-10-16 16:22 UTC by mattjamieson

#256 

Add exports for all `DesktopAgent` methods, delegating to `window.fdc3`. Potentially some clean-up to follow (e.g. move to a separate file).

```typescript
import { broadcast, ContextTypes } from '@finos/fdc3';

const context = {
  type: ContextTypes.Contact,
  id: { email: 'test@example.com' },
};
broadcast(context);
```

2020-10-16 16:45 UTC, mattjamieson commented
Yeah - agreed, doing that now.

2020-10-19 08:26 UTC, mattjamieson commented
#261

2020-10-19 13:34 UTC, rikoe approved these changes

2020-10-19 13:34 UTC, rikoe requested changes
Can we move `methods.ts` under the API folder?

2020-10-19 15:14 UTC, rikoe approved these changes

2020-10-20 10:01 UTC, nkolba approved these changes

2020-10-20 10:29 UTC, merged