450 allow intents to target app instances
finos/FDC3 pull request #509
Opened 2021-11-22 14:11 UTC by kriswest

resolves #450 
Adds an optional `instanceId` field to `AppMetadata`, allowing it to represent specific instances of applications. 

Also updates `open()` to return `AppMetadata` (identifying the instance opened). `raiseIntent()` already returns details of the app resolving an intent, however, this should now always be an `AppMetadata`, with the optional `AppMetadata.instanceId` field set, to represent the app instance that received the intent (and may have been started to do so).

2021-11-24 20:40 UTC, thorsent approved these changes
Great

2021-12-21 06:30 UTC, mattjamieson requested changes

2021-12-21 06:30 UTC, mattjamieson commented on src/api/AppMetadata.ts
> + * Will always includes at least a `name` property, which can be used with [`open`](DesktopAgent#open) and [`raiseIntent`](DesktopAgent#raiseIntent). If the `instanceId` field is set then the `AppMet
```suggestion
 * Will always include at least a `name` property, which can be used with [`open`](DesktopAgent#open) and [`raiseIntent`](DesktopAgent#raiseIntent). If the `instanceId` field is set then the `AppMetadata` object represents a specific instance of the application that may be addressed using that Id.
```

2021-12-21 06:30 UTC, mattjamieson commented on src/api/DesktopAgent.ts
> +   * **Note**,if the intent, context and target app name are all known, it is recommended to instead use `raiseIntent` with the `target` argument.
```suggestion
   * **Note**, if the intent, context and target app name are all known, it is recommended to instead use `raiseIntent` with the `target` argument.
```

2022-01-06 14:10 UTC, mattjamieson approved these changes

2022-01-27 14:57 UTC, rikoe approved these changes

2022-02-04 11:17 UTC, ggeorgievx approved these changes

2022-02-04 11:25 UTC, merged