How to submit a new intent
finos/FDC3 pull request #624
Opened 2022-03-14 11:56 UTC by pauldyson

A guide to how to submit a new intent as discussed with @kriswest. This is dependent on PR 587 as it refers to some of the files in that PR

2022-03-18 12:14 UTC, mistryvinay requested changes
I am seeing differences in how we format the name for intents. Spaces or no-spaces, camel-case etc.

For example for ViewProfile we have the following syntax:
`---
id: ViewProfile
sidebar_label: ViewProfile
title: ViewProfile
hide_title: true
---`

Could we update submit-new-intent to the following please:
`---
id: SubmitNewIntent
sidebar_label: SubmitNewIntent
title: How to Submit a New Intent PR
hide_title: true
---`

2022-03-22 08:48 UTC, pauldyson reviewed
Updated SubmitNewIntent Id

2022-03-22 08:50 UTC, pauldyson commented
> I am seeing differences in how we format the name for intents. Spaces or no-spaces, camel-case etc.
> 
> For example for ViewProfile we have the following syntax:
> 
> ```
> id: ViewProfile
> sidebar_label: ViewProfile
> title: ViewProfile
> hide_title: true
> ---```
> 
> Could we update submit-new-intent to the following please:
> ```---
> id: SubmitNewIntent
> sidebar_label: SubmitNewIntent
> title: How to Submit a New Intent PR
> hide_title: true
> ---```
> ```

I've change the Id but the sidebar_label and title I've left the same. These are consistent with the sidebar labels and titles of other informational pages such as API Overview and Context Data Specification

2022-04-08 11:04 UTC, mistryvinay commented
> > I am seeing differences in how we format the name for intents. Spaces or no-spaces, camel-case etc.
> > For example for ViewProfile we have the following syntax:
> > ```
> > id: ViewProfile
> > sidebar_label: ViewProfile
> > title: ViewProfile
> > hide_title: true
> > ---```
> > 
> > Could we update submit-new-intent to the following please:
> > ```---
> > id: SubmitNewIntent
> > sidebar_label: SubmitNewIntent
> > title: How to Submit a New Intent PR
> > hide_title: true
> > ---```
> > ```
> 
> I've change the Id but the sidebar_label and title I've left the same. These are consistent with the sidebar labels and titles of other informational pages such as API Overview and Context Data Specification

looks good to me. @kriswest are you review and merge this pls.

2022-04-22 10:36 UTC, kriswest commented
This is blocked until #587 is merged as its based on it... Great content though, looking forward to merging it in.

2022-04-22 14:15 UTC, kriswest commented on docs/guides/submit-new-intent.md
> +![Version Selector](assets/version_selector.png)
```suggestion
![Version Selector](../assets/version_selector.png)
```

2022-04-22 14:15 UTC, kriswest commented on docs/guides/submit-new-intent.md
> +![Latest Version Selector](assets/latest_version_selector.png)
```suggestion
![Latest Version Selector](../assets/latest_version_selector.png)
```

2022-04-22 14:16 UTC, kriswest commented on docs/guides/submit-new-intent.md
> +![Next Version](assets/next_version.png)
```suggestion
![Next Version](../assets/next_version.png)
```

2022-04-22 14:24 UTC, kriswest requested changes
Image paths need to be corrected. Have added some links as suggestions at the same time.

Once merged you should be able to go to: https://github.com/singletracksystems/FDC3/blob/how-to-submit-a-new-intent/docs/guides/submit-new-intent.md
and see the images render.

2022-04-22 14:24 UTC, kriswest commented on docs/guides/submit-new-intent.md
> +![View Research](assets/view_research.png)
```suggestion
![View Research](../assets/view_research.png)
```

2022-04-22 14:24 UTC, kriswest commented on docs/guides/submit-new-intent.md
> +![Version Selector](assets/version_selector.png)
```suggestion
![Version Selector](../assets/version_selector.png)
```

2022-04-22 14:24 UTC, kriswest commented on docs/guides/submit-new-intent.md
> +![Latest Version Selector](assets/latest_version_selector.png)
```suggestion
![Latest Version Selector](../assets/latest_version_selector.png)
```

2022-04-22 14:24 UTC, kriswest commented on docs/guides/submit-new-intent.md
> +![Next Version](assets/next_version.png)
```suggestion
![Next Version](../assets/next_version.png)
```

2022-04-22 14:24 UTC, kriswest commented on docs/guides/submit-new-intent.md
> +* website/sidebars.json (look for the 'Intents' property and the 'ids' property within it)
```suggestion
* [src/intents/Intents.ts](https://github.com/finos/FDC3/blob/master/src/intents/Intents.ts)
* [src/intents/standard intents.json](https://github.com/finos/FDC3/blob/master/src/intents/standard%20intents.json)
* [website/sidebars.json](https://github.com/finos/FDC3/blob/master/website/sidebars.json) (look for the 'Intents' property and the 'ids' property within it)
```

2022-04-22 14:24 UTC, kriswest commented on docs/guides/submit-new-intent.md
> +* Any of the Intents documents in docs/intents/ref that are related or relevant to the new Intent (e.g. for the [ViewResearch](../intents/ref/ViewResearch) intent a link was added to the [ViewAnalysi
```suggestion
* [docs/intents/spec.md](https://github.com/finos/FDC3/blob/master/docs/intents/spec.md) in the 'Standard Intents' section (also add the summary from your Intent page)
* Any of the Context documents in [docs/context/ref](https://github.com/finos/FDC3/blob/master/docs/context/ref) that are utilised by the Intent (e.g. for the [ViewResearch](../intents/ref/ViewResearch) intent, each of the [Contact](../context/ref/Contact), [Instrument](../context/ref/Instrument) and [Organization](../context/ref/Organization) Contexts are valid and so links were added to their Context pages)
* Any of the Intents documents in [docs/intents/ref](https://github.com/finos/FDC3/blob/master/docs/intents/ref) that are related or relevant to the new Intent (e.g. for the [ViewResearch](../intents/ref/ViewResearch) intent a link was added to the [ViewAnalysis](../intents/ref/ViewAnalysis) document)
```

2022-04-22 17:09 UTC, mistryvinay approved these changes

2022-05-23 14:13 UTC, merged