Context Data and Intents consolidated update PR
finos/FDC3 pull request #724
Opened 2022-05-18 10:25 UTC by mistryvinay

Consolidated PR for Context Data & Intents (CD&I) updates (each of which is raised as a separate PR into this branch for review by CD&I discussion group members, maintainers and editors).

resolves #600
resolves #681

2022-05-24 10:53 UTC, robmoffat commented
Something going wrong with table rendering, for me at least (checked both Safari and Chrome, multiple pages).

e.g. https://deploy-preview-632--lambent-kulfi-cf51a7.netlify.app/docs/next/context/ref/instrumentlist

<img width="863" alt="Screenshot 2022-05-24 at 11 52 13" src="https://user-images.githubusercontent.com/568673/170018519-be356eee-fd5e-498a-a4d0-8038cc8a1498.png">

2022-05-24 11:56 UTC, kriswest commented
> Something going wrong with table rendering, for me at least (checked both Safari and Chrome, multiple pages).

Yes looks like it affects every table. Odd as its not doing it to me on a local build:
![image](https://user-images.githubusercontent.com/1701764/170027869-5f50639d-5027-4895-8faf-ffc0c4521f7a.png)

The generated HTML is identical but the CSS is different on the netlify build... it's been uglified and altered so that table is display `flex` rather than `block`

2022-05-24 12:26 UTC, kriswest commented on website/siteConfig.js
> +
```suggestion
```

2022-05-25 13:09 UTC, kriswest requested changes
Found a number of things to fix, including standardizing changelogs, sorting lists, incomplete list of standardized contexts etc.. Most have suggestions you can commit @mistryvinay 

I'll go fix the currency schema as I got that wrong.

2022-05-25 13:09 UTC, kriswest commented on src/context/ContextTypes.ts
Actual scratch that, the typegen won't work until this has been merged into main and deployed as the schemas are pulled from the website - hence nothing to do here as this is a release task.

2022-05-25 13:09 UTC, kriswest commented on src/intents/Intents.ts
> +  ViewOrders = 'ViewOrders'
sort list:
```suggestion
export enum Intents {
  StartCall = 'StartCall',
  StartChat = 'StartChat',
  StartEmail = 'StartEmail',
  ViewAnalysis = 'ViewAnalysis',
  ViewChart = 'ViewChart',
  ViewContact = 'ViewContact',
  ViewHoldings = 'ViewHoldings',
  ViewInstrument = 'ViewInstrument',
  ViewInteractions = 'ViewInteractions',
  ViewNews = 'ViewNews',
  ViewOrders = 'ViewOrders'
  ViewProfile = 'ViewProfile',
  ViewQuote = 'ViewQuote',
  ViewResearch = 'ViewResearch',
```

2022-05-25 13:41 UTC, mistryvinay reviewed
Updated PR with suggested feedback and commits.

2022-05-25 17:08 UTC, kriswest commented on CHANGELOG.md
> +* Extended recommend field type conventions for contexts to include types for ids, times, dates, currency codes and country codes. The `fdc3.country` context type was updated to comply with the recom
```suggestion
* Extended recommended field type conventions for contexts to include types for ids, times, dates, currency codes and country codes. The `fdc3.country` context type was updated to comply with the recommended field name for country codes (`COUNTRY_ISOALPHA2`). ([#704](https://github.com/finos/FDC3/pull/704))
```

2022-05-25 20:53 UTC, greyseer256 approved these changes
Minor comments, looks good.

2022-05-25 20:53 UTC, greyseer256 commented on docs/context/spec.md
> +Parsing in Javascript:
```suggestion
Parsing in JavaScript:
```

2022-05-25 20:53 UTC, greyseer256 commented on docs/context/spec.md
> +Parsing in Javascript:
```suggestion
Parsing in JavaScript:
```

2022-05-25 20:53 UTC, greyseer256 commented on docs/intents/ref/StartChat.md
> +        allowAddUser: false, // John won't be auhtorized to add other users to the chat
```suggestion
        allowAddUser: false, // John won't be authorized to add other users to the chat
```

2022-05-27 10:33 UTC, merged