734 return app identifier and add function to retrieve app metadata
finos/FDC3 pull request #751
Opened 2022-06-10 15:32 UTC by kriswest

resolves #734 

Adds a new function to retrieve `AppMetadata` for an `AppIdentifier` and reduces several other return types to only specify `AppIdentifier` rather than `AppMetadata` (which is a superset of `AppIdentifier`'s fields). This helps clarify what fields developers can expect in returns from functions (i.e. only the minimal set in `AppIdentifier`) and that they should manually retrieve any  additional metadata (i.e. an `AppMetadata`) if they need it (for display purposes).

Key areas to review (preview links):

- API overview: https://deploy-preview-751--lambent-kulfi-cf51a7.netlify.app/docs/next/api/spec#reference-apps-or-app-instances-and-retrieve-their-metadata
- `getAppMetadata()` fn reference: https://deploy-preview-751--lambent-kulfi-cf51a7.netlify.app/docs/next/api/ref/desktopagent#getappmetadata
- Other types that had references changed to `AppIdentifier` from `AppMetadata`:
  - [`ContextMetadata`](https://deploy-preview-751--lambent-kulfi-cf51a7.netlify.app/docs/next/api/ref/metadata#contextmetadata)
  - [`IntentResolution`](https://deploy-preview-751--lambent-kulfi-cf51a7.netlify.app/docs/next/api/ref/metadata#intentresolution)
  - [`findInstances`](https://deploy-preview-751--lambent-kulfi-cf51a7.netlify.app/docs/next/api/ref/desktopagent#findinstances)
  - [`open`](https://deploy-preview-751--lambent-kulfi-cf51a7.netlify.app/docs/next/api/ref/desktopagent#open)
  
Finally, please note that the `AppIntent` returned by `findIntent` still uses `AppMetadata` (as the use case will pretty much always require it) as does the `ImplementationMetadata` returned by `getInfo`.

2022-06-13 09:04 UTC, robmoffat commented
One question: 

Is AppMetadata just a subset of the AppD record in this version?  In #734 we were discussing making them equivalent, I think.

2022-06-13 09:18 UTC, robmoffat approved these changes

2022-06-13 10:28 UTC, mattjamieson requested changes
Thanks @kriswest, LGTM. A few tiny tweaks.

2022-06-13 10:28 UTC, mattjamieson commented on docs/api/spec.md
> +To construct workflows between applications, you need to be able to reference specific applications and instance of those applications.
```suggestion
To construct workflows between applications, you need to be able to reference specific applications and instances of those applications. 
```

2022-06-13 10:28 UTC, mattjamieson commented on docs/api/spec.md
> +Additional metadata for an application can be retrieved via the [`fdc3.getAppMetadata(appIdentifier)`](ref/DesktopAgent#getappmetadata) function, which returns an [`AppMetadata`](ref/Metadata#appmeta
```suggestion
Additional metadata for an application can be retrieved via the [`fdc3.getAppMetadata(appIdentifier)`](ref/DesktopAgent#getappmetadata) function, which returns an [`AppMetadata`](ref/Metadata#appmetadata) object. The additional metadata may include a title, description, icons, etc., which may be used for display purposes.
```

2022-06-13 10:28 UTC, mattjamieson commented on src/api/DesktopAgent.ts
> +   * It returns a promise resolving to the intent, its metadata and metadata about the apps and app instances that registered it is returned.
```suggestion
   * It returns a promise resolving to the intent, its metadata and metadata about the apps and app instances that registered that intent.
```

2022-06-13 10:28 UTC, mattjamieson commented on src/api/DesktopAgent.ts
> +   *
```suggestion
   * //Handle a raised intent and log the originating app metadata
   * const listener = fdc3.addIntentListener('StartChat', (contact, metadata) => {
   *   console.log(`Received intent StartChat\nContext: ${contact}\nOriginating app: ${metadata?.source}`);
   *   return;
   * });
   *
```

2022-06-13 10:41 UTC, kriswest commented
well spotted on a few of those, cheers @mattjamieson

2022-06-14 08:59 UTC, kriswest commented
@openfin-johans @openfin-gavin @MichaelMCoates any chance you guys could take a look at this today? I'd like to get it off to the mailing list ASAP so we can then get on with sending out the pre-draft for the adoption vote next week.

The aim of the issue/PR is to reduce the need for the container to reproduce the full AppMetadata (which is growing in size gradually) in situations where it often isn't needed (for example on every context message or IntentResolution) and to provide a way to retrieve it. This should be more efficient for the container and clearer for the developer in terms of workflow (if you need the display metadata for an app, go retrieve it).

2022-06-14 16:11 UTC, openfin-johans approved these changes
It's a peach!

2022-06-15 08:24 UTC, rikoe approved these changes

2022-06-16 17:42 UTC, greyseer256 approved these changes

2022-06-20 10:56 UTC, merged