Fix bad links to AppIdentifier
finos/FDC3 pull request #836
Opened 2022-10-24 12:40 UTC by kriswest

Found a couple of bad links to AppIdentifier in Desktop Agent ref

2022-10-24 15:26 UTC, greyseer256 approved these changes

2022-11-04 17:20 UTC, robmoffat requested changes
You missed some:

```
Launches an app, specified via an [`AppIdentifier`](Metadata#appidentifier) object.
```

2022-11-07 12:28 UTC, kriswest commented
Found and fixed, well spotted @robmoffat

2022-11-07 16:46 UTC, robmoffat approved these changes

2022-11-08 14:07 UTC, mattjamieson approved these changes

2022-11-10 10:27 UTC, merged