Conformance2.0
finos/FDC3 pull request #857
Opened 2022-11-16 12:03 UTC by robmoffat

2022-11-16 15:12 UTC, kriswest requested changes
Partial review highlighting a number of corrections needed

2022-11-16 15:12 UTC, kriswest commented on toolbox/fdc3-conformance/FDC3-2.0-Conformance-Test-Cases.md
> +- `2.0-BasicCL2`: You can call the `fdc3addContextListener` with no context type. The returned listener object has an `ubsubscribe` function.
```suggestion
- `2.0-BasicCL2`: You can call the `fdc3.addContextListener` with a `null` context type. The returned listener object has an `unsubscribe` function.
```

2022-11-16 15:12 UTC, kriswest commented on toolbox/fdc3-conformance/FDC3-2.0-Conformance-Test-Cases.md
> +- `2.0-BasicIL1`: You can call the `fdc3.addIntentListener` on the `DesktopAgent` for an intent, and get back a `Listener` object with `unsubscribe` method.
returns a Promise<Listener> in 2.0

2022-11-16 15:12 UTC, kriswest commented on toolbox/fdc3-conformance/FDC3-2.0-Conformance-Test-Cases.md
> +- `2.0-BasicCH2`: A call to `fdc3.getCurrentChannel()` returns a promise resolving to _null_ if called prior to any `joinChannel`.
Needs correcting to 2.0 function name

2022-11-16 15:12 UTC, kriswest commented on toolbox/fdc3-conformance/FDC3-2.0-Conformance-Test-Cases.md
> +- `2.0-BasicGI1`: A call to `fdc3.getInfo()` returns an object with `fdc3Version` and `provider` properties.
Returns a Promise in 2.0

2022-11-16 15:12 UTC, kriswest commented on toolbox/fdc3-conformance/FDC3-2.0-Conformance-Test-Cases.md
> +- `2.0-BasicAC1`: A call to `fdc3.getOrCreateChannel(<name>)` will return an object matching the `Channel` interface, with properties of `id`, `type`, `broadcast`, `getCurrentContext` and `addContext
returns a  promise in both 1.2 and 2.0

2022-11-16 15:12 UTC, kriswest commented on toolbox/fdc3-conformance/FDC3-2.0-Conformance-Test-Cases.md
> +- `2.0-BasicUC1`: You can call the `fdc3.getSystemChannels()` function and receive a promise containing an array of more than 1 `Channel` objects, each with type and id set.
update to 2.0 function name

2022-11-16 15:12 UTC, kriswest commented on toolbox/fdc3-conformance/FDC3-2.0-Conformance-Test-Cases.md
> +- `2.0-BasicJC1`: You can call `fdc3.joinChannel`, passing in the `id` of one of the system channels.  `fdc3.getCurrentChannel` should then return that joined channel.
update to 2.0 function name.
async in both 1.2 and 2.0 so should be awaited

2022-11-16 15:12 UTC, kriswest commented on toolbox/fdc3-conformance/FDC3-2.0-Conformance-Test-Cases.md
> +- `2.0-BasicUsage1` Perform above test
Please improve test naming

2022-11-16 15:12 UTC, kriswest commented on toolbox/fdc3-conformance/FDC3-2.0-Conformance-Test-Cases.md
> +- `2.0-FilteredUsage4` 3,4,2,1,5
Please improve test naming

2022-11-16 15:12 UTC, kriswest commented on toolbox/fdc3-conformance/FDC3-2.0-Conformance-Test-Cases.md
> + - `2.0-UCFilteredUsageChange`: Perform above test, except that after joining, **A** changes channel with a further _different_ channel.  Check that **A** _doesn't_ receive anything.
```suggestion
 - `2.0-UCFilteredUsageChange`: Perform above test, except that after joining, **A** changes channel to a _different_ channel via a further call to `fdc3.joinUserChannel`.  Check that **A** _doesn't_ receive anything.
```

2022-11-16 15:12 UTC, kriswest commented on toolbox/fdc3-conformance/FDC3-2.0-Conformance-Test-Cases.md
> + - `2.0-UCFilteredUsageLeave`: Perform above test, except that after joining, **A** calls `fdc3.leaveChannel()` and doesn't receive anything.
```suggestion
 - `2.0-UCFilteredUsageLeave`: Perform above test, except that after joining, **A** calls `fdc3.leaveCurrentChannel()` and doesn't receive anything.
```

2022-11-16 15:12 UTC, kriswest commented on toolbox/fdc3-conformance/FDC3-2.0-Conformance-Test-Cases.md
> +| A   | Promise         | Receives a rejection from the open promise with “App Timeout’ from <br>https://fdc3.finos.org/docs/api/ref/Errors#openerror |
```suggestion
| A   | Promise         | Receives a rejection from the open promise with `AppTimeout` from <br>https://fdc3.finos.org/docs/api/ref/Errors#openerror |
```

2022-11-16 15:12 UTC, kriswest commented on toolbox/fdc3-conformance/FDC3-2.0-Conformance-Test-Cases.md
> +- `2.0-AOpensBNoListen`: Skip `fdc3.addContextListener()` above (i.e. no listener was added).
Define expected result (AppTimeout again)

2022-11-21 18:07 UTC, nkolba approved these changes
lgtm

2022-11-25 15:36 UTC, kriswest requested changes
A few wording improvements and a correction to code snippet in 'Raise Intent Result (void result)' steps

2022-11-25 15:36 UTC, kriswest commented on toolbox/fdc3-conformance/FDC3-2.0-Conformance-Test-Cases.md
> +| Test   | 6. receive void result          | The promise received by Test from `resolution.getResult()` should resolve to void. Confirm that the promise could be retrieved before the handler function
This one's description needs improving (the await was making the test impossible to implement):

```suggestion
| Test   | 4. await results          | Test should `const resultPromise = resolution.getResult()` on the `IntentResolution` object returned in the previous step. A promise should be returned quickly.                        |
| B       | 5. return void          | B should return void after a short delay (e.g. 5 seconds).                        |
| Test   | 6. receive void result          | The promise received by Test from `resolution.getResult()` should eventually resolve to void and not be rejected. Additionally, confirm that the promise could be retrieved before the handler function returns. I.e. confirm that `resolution.getResult()` does not block until the result is returned, but rather returns a promise that can be awaited.`     |
```

2022-12-15 17:15 UTC, kriswest commented on toolbox/fdc3-conformance/FDC3-2.0-Conformance-Test-Cases.md
> +  - You should receive a JavaScript Error with the message `ResolveError.NoAppsFound`.
Wrong error specified
```suggestion
  - You should receive a JavaScript Error with the message `ResolveError.IntentDeliveryFailed`.
```

2023-01-09 10:22 UTC, closed without merging