Rm vite workbench 2
finos/FDC3 pull request #923
Opened 2023-03-09 11:49 UTC by robmoffat

2023-03-09 15:14 UTC, mattjamieson commented
Looks good to me, though we should probably back out a few of the changes I made while testing before we merge

2023-03-10 11:02 UTC, robmoffat commented
@mattjamieson @kriswest can you guys give this the once-over?

2023-03-10 11:08 UTC, mattjamieson requested changes
LGTM but I've added suggestions to remove the debugging/trial stuff I added while trying to get the netlify build to work. Assuming it doesn't cause issues it would be better to keep the configs as simple as possible for future maintenance!

2023-03-10 11:08 UTC, mattjamieson commented on website/package.json
> +    "copy-workbench": "del-cli static/toolbox/fdc3-workbench && npm run build-workbench && cd ../toolbox/fdc3-workbench/build && cpy ** ../../../website/static/toolbox/fdc3-workbench --parents && fin
```suggestion
    "copy-workbench": "del-cli static/toolbox/fdc3-workbench && npm run build-workbench && cd ../toolbox/fdc3-workbench/build && cpy ** ../../../website/static/toolbox/fdc3-workbench --parents",
```

2023-03-10 11:08 UTC, mattjamieson commented on toolbox/fdc3-workbench/vite.config.ts
> +		assetsInlineLimit: 0,
```suggestion
```

2023-03-20 14:22 UTC, mattjamieson approved these changes

2023-03-20 18:09 UTC, merged